export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const CLEAR = "CLEAR";

//organization
export const CREATE_ORG_SUCCESS = "CREATE_ORG_SUCCESS";
export const CREATE_ORG_FAILURE = "CREATE_ORG_FAILURE";
export const CHECK_ADMIN_SUCCESS = "CHECK_ADMIN_SUCCESS";
export const CHECK_ADMIN_FAILURE = "CHECK_ADMIN_FAILURE";

//update organization setting
export const UPDATE_ORG_SETTING_SUCCESS = "UPDATE_ORG_SETTING_SUCCESS";
export const UPDATE_ORG_SETTING_FAILURE = "UPDATE_ORG_SETTING_FAILURE";